In [126]:
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np
import os
import sys


In [127]:
def cosine_similarity(ratings):
    sim = ratings.dot(ratings.T)
    if not isinstance(sim, np.ndarray):
        sim = sim.toarray()
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)

In [128]:
y_test = []
x_test = []

In [129]:
for img_path in os.listdir("images"):
    if img_path.endswith(".jpg"):
        img = image.load_img("images/" + img_path, target_size=(224, 224))
        y_test.append(img_path[:])
        x = image.img_to_array(img)
        x = np.expand_dims(x,0)
        if len(x_test) > 0:
            x_test = np.concatenate((x_test, x))
        else:
            x_test = x

In [130]:
x_test = preprocess_input(x_test)

In [131]:
model = VGG16(weights='imagenet', include_top=False)

In [132]:
features = model.predict(x_test)

In [133]:
features_compress = features.reshape(len(y_test), 7 * 7 * 512)
sim = cosine_similarity(features_compress)

In [134]:
len(features_compress)

5

In [84]:
# inputNo =int(np.random.randint(0,len(y_test),1))
# inputNo

2

In [135]:
y_test

['0000.jpg', 'bubufun.jpg', 'cs.jpg', 'img_1.jpg', 'img_2.jpg']

In [145]:
top = np.argsort(-sim[0], axis=0)[0:2]
top

array([0, 1], dtype=int64)

In [146]:
recommend = [y_test[i] for i in top]
print(recommend)

['0000.jpg', 'bubufun.jpg']


In [142]:
print(sim)

[[1.         0.14092879 0.12052704 0.09164122 0.1263466 ]
 [0.14092879 1.         0.09984564 0.15941733 0.19730408]
 [0.12052703 0.09984564 1.         0.12120182 0.14923565]
 [0.09164122 0.15941735 0.12120184 1.         0.24207334]
 [0.1263466  0.19730408 0.14923565 0.24207336 1.        ]]
